# Generated by Django 4.2.4 on 2024-01-26 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientInfo',
            fields=[
                ('pat_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PatientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_type', models.CharField(max_length=20)),
                ('img_link', models.URLField()),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retina.patientinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type', models.CharField(max_length=20)),
                ('comment', models.CharField(blank=True, default='', max_length=200)),
                ('patient_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retina.patientimage')),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_type', models.CharField(max_length=20)),
                ('x_cord', models.FloatField(max_length=10)),
                ('y_cord', models.FloatField(max_length=10)),
                ('radius', models.FloatField(max_length=10)),
                ('patient_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retina.patientimage')),
            ],
        ),
    ]
