# Generated by Django 4.2.4 on 2024-02-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinfo',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
